### PR TITLE
Update User Guide's Supported Machine List To Match Release Notes'

### PR DESCRIPTION
**Pull request by TafThorne**
The Release Notes have been kept more up to date than the User Guide.
This has resulted in the correct data for machine-list.inc being present
in the release-notes source code but the user-guide version becoming out
of date.

This changeset updates the user-guide/source/machine-list.inc to match
to one currently found in release-notes/source/machine-list.inc.  It also 
updates the styling of the table displayed in the User Guide to match that 
of the Release Notes, primarily to avoid the longer field data running off
the end of a line.  

A future update should be made to automatically base the user-guide
version on the release-notes version so that there are not two identical
sets of information to be maintained.  For now the pragmatic thing to do
is bring the user-guide up to date.

### CODE REVIEW

**Comment by TafThorne** [comment]
This pull request replaces #24 and completes the requested update of the user-guide/source/machine-list.inc by way of copying over the release-notes/source/machine-list.inc file.

**Comment by TafThorne** [comment]
I agree that checkin is probably useless as it is overwritten by the latter
copy update. I'm not that aware of how GitHub's workflow or this project is
run so I left it in the branch as it was part of the history that led to
this pull request. Can the whole request be pulled as a single change or do
I need to redo the two useful changes in the morning?

**Comment by TafThorne** [comment]
There is no easy way for me to remove the commit without re-doing my work from scratch.  Could the maintainer doing the merge use the https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits Squash and Merge option to replace my 3 commits with a single one with a single commit message?  If I recall correctly this will take the subject of this pull request as the summary line and my opening comment as the commit log.

**Comment by otavio** [comment]
You can rebase it and drop the patch.

**Comment by TafThorne** [comment]
You guys really arn't going to let me be lasy are you.  Instead of clicking a different accept button I am going to have to go re-base :'(

**Comment by TafThorne** [comment]
OK.  I have rebased my changes on to my copy of master so that the "add freescale..." commit is dropped or squashed or whatever.  

Can I update this pull request to use those changes somehow or do I have to discard it and start a new one?

**Comment by TafThorne** [comment]
Or do I need to rebase and push the change to my branch history?  That sounds a little unpleasant as it would mess up the repo of anyone who had cloned and used my feature branch (slim odds I realise).  

If that is the case I have a mangled version on my PC that I can push to my GitHub repo if that is how I should update this pull request.

**Comment by angolini** [comment]
I'm not sure if GH allows a pull-request update. So I would create a new branch and a new pull request.

I'm closing this one. You can decide if you want to keep it closed or if you want to remove it.

No lazy boys allowed :D

**Comment by angolini** [comment]
Just figured out there is no need to open a new PR:

https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/

You can create a new branch and *change* the branch of your PR

**Comment by TafThorne** [comment]
> You can create a new branch and change the branch of your PR

It seems I can change the branch that I am requesting things get pulled onto but not which branch that I am asking you guys to pull from.  
image

> No lazy boys allowed :D

:'(

> I'm not sure if GH allows a pull-request update. So I would create a new branch and a new pull request.

I think I found some documentation that says I may do a `git push --force` to re-write the history of the branch I based the pull request on.  I shall try that now.  I do not expect that I can break GitHub so easily but if I do, I am sorry internetz.

**Comment by TafThorne** [comment]
Looks like my updated branch (created 2 days ago) was accepted by GitHub when I did a `git push --force` just now.   
image

@angolini the merge should be as you request now.  It seems that Pull Requests will still work when the branch they reference is rebased and a force push is used to update it,.

**Comment by TafThorne** [comment]
Thank you.  I will now delete my branch and tidy up my fork.

**Pull request merged**
