### PR TITLE
Updated data against Kirkstone release

### PR DESCRIPTION
**Pull request by angolini**
I'm creating the PR so we can start review it, but I see the contribution sections are not good

### CODE REVIEW

**Review by otavio — CHANGES_REQUESTED** [review]
Items which we need to fix:

- [ ] contributions statistics
- [ ] ensure `ventana` board builds (old `u-boot`) or remove
- [ ] ensure `imx6qdl-variscite-som` board builds (old `u-boot`) or remove
- [ ] ensure `imx7d-remarkable2` board builds (old `u-boot`) or remove
- [ ] improve SoC tree
- [ ] add `p2020rdb` machine description
- [ ] add SoC field on `imx8dx-mek`
- [ ] add SoC field on `imx8dxl-ddr3l-evk`
- [ ] add SoC field on `imx8dxl-lpddr4-evk`
- [ ] add SoC field on `imx8qm-mek`

**Comment by otavio** [comment]
@angolini, @ossanes did part of this in https://github.com/Freescale/meta-freescale/pull/1140

**Comment by angolini** [comment]
Is there any plan on the machines `ventana`, `imx6qdl-variscite-som` and `imx7d-remarkable2`, @Ossanes? I'm asking because if there is no plan to update it, I can remove them

**Comment by otavio** [comment]
If build fails, I'd remove.

**Comment by angolini** [comment]
`ventana` and `imx7d-remarkable2` fails
 imx6qdl-variscite-som works

I'm preparing the PR

**Comment by angolini** [comment]
I'm on my way, but it takes some time... @otavio

**Comment by angolini** [comment]
Closing this as we are not working. In case we have time to go back to this, we can reopen.

**Pull request closed without merging**
