### PR TITLE
Add Freescale LS1021A Tower System to machine-list.inc

### PR DESCRIPTION
**Pull request by TafThorne**
The Freescale QorIQ® LS1021A Tower® System Module is a supported
platform listed as a supported machine when sourcing the ./setup-
environment file.

According to the details in the meta-fsl-
arm/conf/machine/ls1021atwr.conf this is a ls102xa SoC item is supplied
by the meta-fsl-arm layer.

### CODE REVIEW

**Comment by TafThorne** [comment]
This is the same as my (Thomas Thorne of Net2Edge Limited) earlier attempt to update the community documentation via email patches.  As getting my emails sorted out is not going to be quick I am trying via the GitHub method.  

@angolini was kind enough to review this patch and said: 

> >> 0001-Add-Freescale-LS1021A-Tower-System-to-machine-list.i.patch
> 
> This patch adds only LS1021A-Tower to the table. Can you, please try
> to update that table using the same content we have in Release Notes?
> 
> /code/yocto/master/sources/Documentation$ find -name *machine-list.inc
> ./user-guide/source/machine-list.inc
> ./release-notes/source/machine-list.inc
> 
> I think only copying over the file would be enough.
> 

Unfortunately I do not understand what is being requested of me, so I cannot add an update patch yet.  As far as I can tell this adds a complete table entry the same as the rest of the rows in that file.  Is it that I should update the _Name_ in the release-notes version to "Freescale QorIQ® LS1021A Tower® System Module" ?

**Comment by angolini** [comment]
Regarding the question on https://github.com/Freescale/Documentation/pull/24#issuecomment-249627166, the file machine-list.inc is automatically updated by an script every time the Release Notes is bumped.

It means that the file https://github.com/Freescale/Documentation/blob/master/release-notes/source/machine-list.inc is newer than the file https://github.com/Freescale/Documentation/blob/master/user-guide/source/machine-list.inc.

So, I'm asking you to update the file using the latest list of supported machines from release notes (release-notes/source/machine-list.inc), instead of only adding a reference for LS1021A Tower. And I think coping over the file from release-notes directory into user-guide directory would be enough.

@TafThorne , please let me know what you think.

**Comment by TafThorne** [comment]
>  the file machine-list.inc is automatically updated by an script every time the Release Notes is bumped.

If the user-guide machine-list.inc file is derived or automatically generated, why is it committed to source control?  

I am also a little confused as the 'release-notes/source/machine-list.inc' file already contains an entry for the LS1021a-TWR board.  If the user-guide was updated automatically, why does the LS1021a-TWR not already appear in the list, without my changes?

**Comment by angolini** [comment]
The machine-list.inc is used to generate both the PDF and the HTML for the Release Notes, so we decided to track the changes on that file (and other files).

We've been automatically updating only the Release Notes, not the User Guide.

The file in release notes contains the LS1021 since it was included in meta-fsl-arm, because we've been updating it a lot. In fact, only User Guide was outdated.

**Comment by TafThorne** [comment]
I meant if there are two source files with the same data, why not have only one source file?  

If you need a copy of the file in the user-guide source are the user-guide build could copy over the file from the release-notes source file.

**Comment by angolini** [comment]
Well, you are right. I remember we talked about this at that time, but I really don't remember if we really have decided something. I think at that time, we still used to meet with community monthly and I think we talked about this topic during some of that meetings. 

My guess is that we started to work with User Guide, asked for community help, and other priorities made us change our focus out of the user guide text.

I also remember I have a branch on my fork making some changes on UG I have never ended....

Today, I think you can either update the file completely, or propose a better way to update this automatically. We can discuss this here, or via email/hangout if you prefer. What do you think?

**Comment by TafThorne** [comment]
I am not in a rush to get the documentation updated so if another time would be better for you or other members of the community that would be fine with me.  

I would be happy doing a copy paste update from the updated release-notes to the user-guide so as to get the files up to date today.  Then I/we can work on a separate change to automatically use one source file to generate both tables, maybe we make an issue ticket for that here to remind me. 

I am happy to discuss that here, via email or a hangouts.  Whatever fits best with the normal workflow for you or the project.

**Comment by angolini** [comment]
I prefer the "add the manual update today and work to enhance the process after that" approach :)

**Comment by TafThorne** [comment]
I shall create a new pull request titled "Update User Guide's machine-list.inc To Match Release Notes'".

**Pull request closed without merging**
